import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../core/models/match_score.dart';

class MatchReportPdf {
  // ── Public API ─────────────────────────────────────────────────────────────

  static Future<void> printReport(LiveMatch match) async {
    try {
      await Printing.layoutPdf(
        name: '${match.teamA} vs ${match.teamB}',
        onLayout: (_) async => generate(match),
      );
    } catch (e) { /* ignored */ }
  }

  static Future<Uint8List> generate(LiveMatch match) async {
    final pdf = pw.Document(
      title: '${match.teamA} vs ${match.teamB} — Match Report',
    );

    if (match.sport == MatchSport.cricket && match.cricket != null) {
      pdf.addPage(_cricketPage(match));
    } else {
      pdf.addPage(_genericPage(match));
    }

    return pdf.save();
  }

  // ── Cricket report ─────────────────────────────────────────────────────────

  static pw.Page _cricketPage(LiveMatch match) {
    final cr = match.cricket!;
    final date = match.createdAt;
    final dateStr = '${date.day}/${date.month}/${date.year}';

    return pw.Page(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(32),
      build: (pw.Context ctx) {
        return pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            // ── Header ──────────────────────────────────────────────────────
            pw.Container(
              width: double.infinity,
              padding: const pw.EdgeInsets.all(16),
              decoration: pw.BoxDecoration(
                color: PdfColors.red900,
                borderRadius: pw.BorderRadius.circular(8),
              ),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.center,
                children: [
                  pw.Text(
                    '${match.teamA}  vs  ${match.teamB}',
                    style: pw.TextStyle(
                      color: PdfColors.white,
                      fontSize: 20,
                      fontWeight: pw.FontWeight.bold,
                    ),
                    textAlign: pw.TextAlign.center,
                  ),
                  pw.SizedBox(height: 6),
                  pw.Text(
                    '${match.format}  ·  ${match.venue}  ·  $dateStr',
                    style: pw.TextStyle(
                        color: PdfColors.white.shade(0.7), fontSize: 10),
                    textAlign: pw.TextAlign.center,
                  ),
                ],
              ),
            ),
            pw.SizedBox(height: 16),

            // ── Man of the Match ─────────────────────────────────────────────
            if (cr.manOfMatch != null) ...[
              pw.Container(
                padding: const pw.EdgeInsets.symmetric(
                    horizontal: 12, vertical: 8),
                decoration: pw.BoxDecoration(
                  border: pw.Border.all(color: PdfColors.red),
                  borderRadius: pw.BorderRadius.circular(6),
                ),
                child: pw.Row(children: [
                  pw.Text('★ Man of the Match:  ',
                      style: pw.TextStyle(
                          color: PdfColors.red,
                          fontWeight: pw.FontWeight.bold,
                          fontSize: 12)),
                  pw.Text(cr.manOfMatch!,
                      style: pw.TextStyle(
                          fontWeight: pw.FontWeight.bold, fontSize: 12)),
                ]),
              ),
              pw.SizedBox(height: 12),
            ],

            // ── Innings ───────────────────────────────────────────────────────
            ...cr.innings.asMap().entries.expand((e) {
              final inn = e.value;
              final num = e.key + 1;
              return [
                _inningsSection(inn, num),
                pw.SizedBox(height: 14),
              ];
            }),

            // ── Result ────────────────────────────────────────────────────────
            if (cr.matchResult.isNotEmpty) ...[
              pw.Divider(),
              pw.SizedBox(height: 8),
              pw.Center(
                child: pw.Text(
                  cr.matchResult,
                  style: pw.TextStyle(
                      color: PdfColors.red900,
                      fontWeight: pw.FontWeight.bold,
                      fontSize: 14),
                  textAlign: pw.TextAlign.center,
                ),
              ),
            ],

            pw.Spacer(),
            pw.Divider(),
            pw.Text(
              'Generated by MySportsBuddies',
              style: const pw.TextStyle(
                  color: PdfColors.grey, fontSize: 9),
            ),
          ],
        );
      },
    );
  }

  static pw.Widget _inningsSection(CricketInnings inn, int num) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        // Innings header
        pw.Container(
          width: double.infinity,
          padding:
              const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 6),
          color: PdfColors.grey200,
          child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text('Innings $num — ${inn.battingTeam}',
                    style: pw.TextStyle(
                        fontWeight: pw.FontWeight.bold, fontSize: 12)),
                pw.Text(inn.fullStr,
                    style: pw.TextStyle(
                        color: PdfColors.red900,
                        fontWeight: pw.FontWeight.bold,
                        fontSize: 12)),
              ]),
        ),
        pw.SizedBox(height: 6),

        // Batting
        if (inn.batsmen.isNotEmpty) ...[
          pw.Text('BATTING',
              style: const pw.TextStyle(
                  color: PdfColors.grey, fontSize: 9)),
          pw.SizedBox(height: 4),
          _battingTable(inn.batsmen),
          pw.SizedBox(height: 8),
        ],

        // Bowling
        if (inn.bowlers.isNotEmpty) ...[
          pw.Text('BOWLING',
              style: const pw.TextStyle(
                  color: PdfColors.grey, fontSize: 9)),
          pw.SizedBox(height: 4),
          _bowlingTable(inn.bowlers),
          pw.SizedBox(height: 8),
        ],

        // Extras
        pw.Text(
          'Extras: ${inn.extras}  (W ${inn.wides}, NB ${inn.noBalls}, B ${inn.byes}, LB ${inn.legByes})',
          style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
        ),

        // FOW
        if (inn.fow.isNotEmpty) ...[
          pw.SizedBox(height: 6),
          pw.Text('Fall of Wickets:',
              style: const pw.TextStyle(
                  color: PdfColors.grey, fontSize: 9)),
          pw.SizedBox(height: 2),
          pw.Text(
            inn.fow
                .map((f) =>
                    '${f.wicketNum}-${f.runs} (${f.batsmanName}, ${f.oversStr})')
                .join('   '),
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
          ),
        ],
      ],
    );
  }

  static pw.Widget _battingTable(List<CricketBatsman> batsmen) {
    const headerStyle = pw.TextStyle(
        fontSize: 9, color: PdfColors.grey);
    const cellStyle = pw.TextStyle(fontSize: 10);
    final boldCell =
        pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold);

    return pw.Table(
      border: pw.TableBorder(
        horizontalInside: const pw.BorderSide(color: PdfColors.grey300, width: 0.5),
      ),
      columnWidths: {
        0: const pw.FlexColumnWidth(3),
        1: const pw.FlexColumnWidth(0.8),
        2: const pw.FlexColumnWidth(0.8),
        3: const pw.FlexColumnWidth(0.6),
        4: const pw.FlexColumnWidth(0.6),
        5: const pw.FlexColumnWidth(1),
      },
      children: [
        pw.TableRow(
          decoration: const pw.BoxDecoration(color: PdfColors.grey100),
          children: ['Batsman', 'R', 'B', '4s', '6s', 'SR']
              .map((h) => pw.Padding(
                    padding: const pw.EdgeInsets.symmetric(
                        horizontal: 4, vertical: 4),
                    child: pw.Text(h, style: headerStyle),
                  ))
              .toList(),
        ),
        ...batsmen.map(
          (b) => pw.TableRow(children: [
            pw.Padding(
              padding:
                  const pw.EdgeInsets.symmetric(horizontal: 4, vertical: 3),
              child: pw.Text(
                b.isStriker ? '* ${b.name}' : b.name,
                style: b.isOut ? cellStyle : boldCell,
              ),
            ),
            _tc('${b.runs}', bold: true),
            _tc('${b.balls}'),
            _tc('${b.fours}'),
            _tc('${b.sixes}'),
            _tc(b.srStr),
          ]),
        ),
      ],
    );
  }

  static pw.Widget _bowlingTable(List<CricketBowler> bowlers) {
    const headerStyle = pw.TextStyle(fontSize: 9, color: PdfColors.grey);
    return pw.Table(
      border: pw.TableBorder(
        horizontalInside: const pw.BorderSide(color: PdfColors.grey300, width: 0.5),
      ),
      columnWidths: {
        0: const pw.FlexColumnWidth(3),
        1: const pw.FlexColumnWidth(0.8),
        2: const pw.FlexColumnWidth(0.6),
        3: const pw.FlexColumnWidth(0.8),
        4: const pw.FlexColumnWidth(0.6),
        5: const pw.FlexColumnWidth(1),
      },
      children: [
        pw.TableRow(
          decoration: const pw.BoxDecoration(color: PdfColors.grey100),
          children: ['Bowler', 'O', 'M', 'R', 'W', 'Eco']
              .map((h) => pw.Padding(
                    padding: const pw.EdgeInsets.symmetric(
                        horizontal: 4, vertical: 4),
                    child: pw.Text(h, style: headerStyle),
                  ))
              .toList(),
        ),
        ...bowlers.map(
          (b) => pw.TableRow(children: [
            pw.Padding(
              padding:
                  const pw.EdgeInsets.symmetric(horizontal: 4, vertical: 3),
              child: pw.Text(b.name,
                  style: b.wickets > 0
                      ? pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10)
                      : const pw.TextStyle(fontSize: 10)),
            ),
            _tc(b.oversStr),
            _tc('${b.maidens}'),
            _tc('${b.runs}'),
            _tc('${b.wickets}', bold: b.wickets > 0),
            _tc(b.ecoStr),
          ]),
        ),
      ],
    );
  }

  // ── Generic report ─────────────────────────────────────────────────────────

  static pw.Page _genericPage(LiveMatch match) {
    final scoreA = _scoreLabel(match, 'A');
    final scoreB = _scoreLabel(match, 'B');
    final date = match.createdAt;
    final dateStr = '${date.day}/${date.month}/${date.year}';

    return pw.Page(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(40),
      build: (pw.Context ctx) => pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.center,
        mainAxisAlignment: pw.MainAxisAlignment.center,
        children: [
          pw.Text(match.sportDisplayName,
              style: pw.TextStyle(
                  color: PdfColors.red900,
                  fontSize: 14,
                  fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 8),
          pw.Text('Match Report',
              style: pw.TextStyle(
                  fontSize: 22, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 20),
          pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.center,
              children: [
                pw.Column(children: [
                  pw.Text(match.teamA,
                      style: const pw.TextStyle(fontSize: 14)),
                  pw.Text(scoreA,
                      style: pw.TextStyle(
                          fontSize: 40, fontWeight: pw.FontWeight.bold)),
                ]),
                pw.SizedBox(width: 40),
                pw.Text('—',
                    style: const pw.TextStyle(
                        fontSize: 32, color: PdfColors.grey)),
                pw.SizedBox(width: 40),
                pw.Column(children: [
                  pw.Text(match.teamB,
                      style: const pw.TextStyle(fontSize: 14)),
                  pw.Text(scoreB,
                      style: pw.TextStyle(
                          fontSize: 40, fontWeight: pw.FontWeight.bold)),
                ]),
              ]),
          pw.SizedBox(height: 20),
          if (match.venue.isNotEmpty)
            pw.Text('📍 ${match.venue}',
                style: const pw.TextStyle(
                    fontSize: 11, color: PdfColors.grey700)),
          pw.Text(dateStr,
              style:
                  const pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
          pw.Spacer(),
          pw.Divider(),
          pw.Text('Generated by MySportsBuddies',
              style: const pw.TextStyle(
                  fontSize: 9, color: PdfColors.grey)),
        ],
      ),
    );
  }

  // ── Helpers ────────────────────────────────────────────────────────────────

  static pw.Widget _tc(String text, {bool bold = false}) => pw.Padding(
        padding:
            const pw.EdgeInsets.symmetric(horizontal: 4, vertical: 3),
        child: pw.Text(text,
            style: bold
                ? pw.TextStyle(
                    fontSize: 10, fontWeight: pw.FontWeight.bold)
                : const pw.TextStyle(fontSize: 10)),
      );

  static String _scoreLabel(LiveMatch m, String side) {
    if (m.sport == MatchSport.football) {
      return side == 'A'
          ? '${m.football?.teamAGoals ?? 0}'
          : '${m.football?.teamBGoals ?? 0}';
    }
    if (m.sport == MatchSport.basketball) {
      return side == 'A'
          ? '${m.basketball?.teamATotal ?? 0}'
          : '${m.basketball?.teamBTotal ?? 0}';
    }
    if (m.sport == MatchSport.hockey) {
      return side == 'A'
          ? '${m.hockey?.teamAGoals ?? 0}'
          : '${m.hockey?.teamBGoals ?? 0}';
    }
    return '—';
  }
}
