// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi4O6pAGvw1OVDpvYZLMtavpzzyAEZmR8',
    appId: '1:793247401031:web:0541d44686ee8e47645d62',
    messagingSenderId: '793247401031',
    projectId: 'mysportsbuddies-4d077',
    authDomain: 'mysportsbuddies-4d077.firebaseapp.com',
    databaseURL: 'https://mysportsbuddies-4d077-default-rtdb.firebaseio.com',
    storageBucket: 'mysportsbuddies-4d077.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV6wjivEXJ23ZGfsOD-Q6BbAzPVbOpqVM',
    appId: '1:793247401031:android:186038342975c747645d62',
    messagingSenderId: '793247401031',
    projectId: 'mysportsbuddies-4d077',
    databaseURL: 'https://mysportsbuddies-4d077-default-rtdb.firebaseio.com',
    storageBucket: 'mysportsbuddies-4d077.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdrgwJIAxj_EQGKDOLRVWn9OgSPMCMDso',
    appId: '1:793247401031:ios:6b3ef6069de3b8a0645d62',
    messagingSenderId: '793247401031',
    projectId: 'mysportsbuddies-4d077',
    databaseURL: 'https://mysportsbuddies-4d077-default-rtdb.firebaseio.com',
    storageBucket: 'mysportsbuddies-4d077.firebasestorage.app',
    androidClientId: '793247401031-outb32irumi8v1r6ok63rleg3h8bb5pn.apps.googleusercontent.com',
    iosClientId: '793247401031-73cic8h1k0mg5tc61tqpo0s5uuhqcm0q.apps.googleusercontent.com',
    iosBundleId: 'com.mysportsbuddies.app',
  );
}
